### ISSUE TITLE
in-header.tex causing missing math symbols...

### ISSUE THREAD

**Issue by olearydj** [nmfs-opensci/quarto_titlepages_v1#1]
### Description

Hello. I'm new to LaTeX and Quarto, so please take these reports with a grain of salt. Also, I'm using v1 to simplify my introduction to this publishing system. I hope not to waste your time. I greatly appreciate you sharing these templates and instructions.

When using the `academic-static` template to create pdfs using the `scrbook` document class, I find that some math symbols are missing if the provided `in-header.tex` file is included. Using the sample document you provided, note the lack of the following symbols in the screenshot below: ellipsis ($\ldots\$), mu ($\mu$), sigma ($\sigma$), infinity ($\infty$), summation ($\Sigma$), square root ($\sqrt{}$), minus ($-$), and script N ($\mathcal{N}$).

<img width="436" alt="image" src="https://user-images.githubusercontent.com/42705243/207384486-0267856e-8382-4af5-af98-4829864ebada.png">

Removing these lines:
```yaml
    include-in-header: 
      - "tp_v1/in-header.tex"
```
... corrects the problem:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/42705243/207385218-f73919ab-7f67-45e7-86d1-89a2e07d6436.png">

### Steps to Reproduce
The complete YAML I've used is below. Also attached is a minimal zip of the test folder.
[test_font.zip](https://github.com/nmfs-opensci/quarto_titlepages_v1/files/10219908/test_font.zip)

```yaml
title: "test_font_1"
editor: source
format:
  pdf:
    documentclass: scrbook
    classoption: ["twoside=false", "open=any"]

    number-sections: true
    template-partials:
      - "tp_v1/before-body.tex"
      - "tp_v1/_titlepage.tex"
    include-in-header: 
      - "tp_v1/in-header.tex"
    toc: true
    toc-depth: 3
    lof: true
    lot: true
    margin-top: 1in
    margin-left: 1.5in  # allow for binding; use 1in otherwise
    margin-right: 1in
    margin-bottom: 1in
    fontsize: 12pt
```

Best!
Dan
